"""add_page_number_to_books

Revision ID: 88ca9949b1ab
Revises: 5ee87fc2ef9c
Create Date: 2026-07-21 15:33:39.321470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ca9949b1ab'
down_revision: Union[str, Sequence[str], None] = '5ee87fc2ef9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'page_number')
    # ### end Alembic commands ###
