"""add_birth_column_to_authors

Revision ID: dc2733888f71
Revises: 5be71d5995bb
Create Date: 2026-07-14 17:01:43.942770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2733888f71'
down_revision: Union[str, Sequence[str], None] = '5be71d5995bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'birth_date')
    # ### end Alembic commands ###
